server:
  port: 4000
  shutdown: "graceful"

# If you want to use a database then uncomment the `group:, readiness: and include: "db"`
# lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: info # should we have more?

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dev.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/test/"
  application:
    name: Dev Test

  logging:
    level:
      root: INFO
      uk.gov.hmcts.reform.dev: DEBUG
      uk.gov.hmcts.reform.dev.controllers: DEBUG
      uk.gov.hmcts.reform.dev.services: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: taskmaster
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
